# Site settings
title:          见欢的博客
description:    "Think big, go deep."
# baseurl:        "/tale"
url:            "https://gannicus-yu.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         gannicus
  url:          https://gannicus-yu.github.io
  email:        gannicus_yu@163.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5


